name: metl
channels:
  - conda-forge
dependencies:
  - python=3.9.17
  - pytorch::pytorch=1.12.1
  - pytorch-lightning=1.7.7
  - torchmetrics=0.10.2
  - numpy=1.23.4
  - pandas=2.0.3
  - scipy=1.9.3
  - scikit-learn=1.1.3
  - networkx=2.6.3
  - tqdm=4.66.2
  - pyyaml=6.0
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - biopandas=0.2.7
  - shortuuid=1.0.1
  - umap-learn=0.5.5
  - bokeh=2.4.3
  - datashader=0.14.2
  - holoviews=1.15.1
  - colorcet=3.0.0
  - pynndescent=0.5.7
  - jupyter=1.0.0
  - jupyterlab=4.1.2
  - ipywidgets=8.1.2
  - requests=2.28.1
  - pytables=3.7.0
  - pip=22.3.1
  - wandb=0.13.5
  - tensorboard=2.11.0
  - memory_profiler=0.58.0
  - rich=13.7.0
  - pyqt=5.15.7
  - sqlalchemy=1.4.43
  - aenum=3.1.11
  - connectorx=0.3.2
  - configargparse=1.5.3
  - torchinfo=1.8.0
  - biopython=1.83
  - mkl=2023.2.0
  - pip:
      - jsonargparse[signatures]==4.15.0
      - matplotlib-label-lines==0.5.1
      - fair-esm==2.0.0
      - torchextractor==0.3.0
      - adjusttext==0.8
